### PR TITLE
Throw exception i.o. fatal error if file does not exist in parseFile

### LINKED ISSUE #18: Fatal error if filename given to parseFromFile does not exist
If the first parameter of `Comment::parseFile` is not an existing file you'll encounter a fatal error.

It would probably be better to throw an exception (RuntimeException or maybe an InvalidArgumentException?) if the file does not exist, so it can be caught in the code.

Simple test case:

```php
<?php
require_once 'vendor/autoload.php';
use Ahc\Json\Comment;

Comment::parseFromFile('does-not-exist.json');
```

Outputs `PHP Fatal error:  Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, bool given`, instead of throwing an exception.

### PR DESCRIPTION
**Pull request by martijnengler**
Fixes #18

### CODE REVIEW

File: src/Comment.php [hunk 1]
```diff
@@ -204,6 +204,14 @@ public static function parse(string $json, bool $assoc = false, int $depth = 512
 
     public static function parseFromFile(string $file, bool $assoc = false, int $depth = 512, int $options = 0)
     {
+        if (!file_exists($file)) {
+            throw new \RuntimeException(sprintf('File %s does not exist', $file));
+        }
+
+        if (!is_file($file)) {
+            throw new \RuntimeException(sprintf('%s is not a file', $file));
```
Comment (adhocore) [inline src/Comment.php:212]: maybe we can use a better exception msg here?

**Review by adhocore — CHANGES_REQUESTED** [review]
thanks, but left some feedback

File: src/Comment.php [hunk 2]
```diff
@@ -204,6 +204,14 @@ public static function parse(string $json, bool $assoc = false, int $depth = 512
 
     public static function parseFromFile(string $file, bool $assoc = false, int $depth = 512, int $options = 0)
     {
+        if (!file_exists($file)) {
```
Comment (adhocore) [inline src/Comment.php:207]: this check should not be necessary. is_file check must be enough

File: src/Comment.php (hunk 1 above)
Comment (adhocore) [reply src/Comment.php:212]: also , maybe better to use InvalidArgumentException?

File: src/Comment.php (hunk 2 above)
Comment (martijnengler) [reply src/Comment.php:207]: I guess that depends on how specific you want to be with exceptions. If we don't split it, the exception must be something like "[given arg] is not a file or does not exist", which is a bit more vague.

But maybe more specific testing needs to be done on the "client" side, if the difference matters. I can see the argument that it's not the responsiblity of this class to check for the difference.

File: src/Comment.php (hunk 1 above)
Comment (martijnengler) [reply src/Comment.php:212]: Do you have a suggestion for a better message? I think "[filename] does not exist or is not a file" (or maybe "not a *regular* file"?) is pretty much what you would need to know, right?

I'm not sure about the InvalidArgumentException, since that's seems more for things where the wrong *type* is provided. So for example if an object was given instead of a filename.
But like I said in the issue: I'm not sure myself.

Comment (adhocore) [reply src/Comment.php:212]: yes please. i would say:
- only is_file check
- msg: [filename] does not exist or is not a file
- exception: InvalidArgumentException

that's all. 😎

File: src/Comment.php (hunk 2 above)
Comment (martijnengler) [reply src/Comment.php]: Updated all points

**Review by adhocore — APPROVED** [review]

**Comment by adhocore** [comment]
merging it soon n releasing new version together. thanks 👍

**Comment by adhocore** [comment]
anyways if you use angular format commit msg then the [release](https://github.com/adhocore/please) tool will nicely pick it up n attribute to you
